apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- oauth.yaml
- admin-rb.yaml

# we don't need name suffixes
generatorOptions:
  disableNameSuffixHash: true

# generate a secret with everything from client-secret.env
secretGenerator:
- name: google-sso-secret
  namespace: openshift-config
  type: generic
  envs:
    - client-secret.env

# generate a config map to get keys from client-secret.env
configMapGenerator:
- name: tmp-props
  envs:
  - client-secret.env

# Use the vars in ConfigMap google-client to update 
# properties in OAuth and admin role binding
replacements:
# Update clientID in OAuth/spec/identityProviders
- source:
    fieldPath: data.clientID
    kind: ConfigMap
    name: tmp-props
    version: v1
  targets:
  - fieldPaths:
    - spec.identityProviders.0.google.clientID
    select:
      group: config.openshift.io
      kind: OAuth
      name: cluster
      version: v1

# Update user name in admin-rb.yaml
- source:
    fieldPath: data.adminUser
    kind: ConfigMap
    name: tmp-props
    version: v1
  targets:
  - fieldPaths:
    - subjects.0.name
    select:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-admin-23435
      version: v1
