apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: rhdh
  labels:
    app.kubernetes.io/instance: rhdh
    app.kubernetes.io/name: backstage  
spec:
  application:
    appConfig:
      configMaps:
        - name: rhdh-app-config
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      secrets:
        - name: rhdh-secrets
        - name: github-secrets
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
