# Use this file to configure your dynamic plugins
# If you're using any environment variables, please define them
# in backend-secret.env
includes:
  - dynamic-plugins.default.yaml
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic'
    disabled: false
    pluginConfig: {}
  - package: './dynamic-plugins/dist/backstage-plugin-kubernetes'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-topology'
    disabled: false

