apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhdh

resources:
- ns.yaml
- backstage.yaml


# we don't need name suffixes
generatorOptions:
  disableNameSuffixHash: true

# generate a secret with everything from github-secret.env
secretGenerator:
- name: github-secrets
  type: Opaque
  envs:
    - github-secret.env
- name: rhdh-secrets
  type: Opaque
  envs:
    - backend-secret.env
  
# generate a config map to get keys from github-secret.env
configMapGenerator:
- name: rhdh-app-config
  files: 
    - app-config-rhdh.yaml
- name: dynamic-plugins-rhdh
  files:
    - dynamic-plugins.yaml    
- name: rbac-policy
  files:
    - rbac-policy.csv