apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# install namespaces for operators
- ns-op-rh.yaml
- ns-op-dt.yaml

# install prereq operators
- elastic.yaml
- jaeger.yaml
- kiali.yaml

# install servicemesh operator
- mesh.yaml

# create control plane 
- control-plane.yaml

